### ISSUE TITLE
New Relic Plugin has not all values

### ISSUE THREAD

**Issue by dmasur** [secondimpression/newrelic_sidekiq_agent#2]
Hi there,

we installed your awesome plugin, but the enqueued chart is empty. The values are stored in Jobs/Count/Pending, is it possible that the sidekiq dashboard did not find this value. Is the source of the dashboard opensource too? I cannot find it to debug this more.

Thanks for your work,
Dominik

**Comment by eksoverzero** [comment]
Hi,

Sorry for the late reply. This plugin has gone through several issues on the NR plugin platform. Loosing ownership and duplicates etc. I am testing it now. Is it possible to please sen your Redis (service and gem) and Sidekiq versions please?

When you say 'dashboard' I assume you'r speaking about the NR plugin screen layout? If this is the case: It's not coded, it's created when publishing a plugin. So if I find the nil values too and it turns out to be the chart reading the wrong value, then when I edit the chart my side that change is replicated into all the charts using the plugin. 

You can build you own chart/s if you like, you can just replublish the plugin. Just change the GUID on line 14 here: https://github.com/secondimpression/newrelic_sidekiq_agent/blob/master/newrelic_sidekiq_agent. Then run the plugin as normal. A new plugin tab will appear on NR for you. You can then edit the plugin, creating dashboards and charts as you see fit.

I'll update here once I know more. Sorry for the trouble caused

**Comment by eksoverzero** [comment]
The enqueued chart has been fixed in NR

**Comment by hobakill** [comment]
We're having similar issues as to what's happening above. The plugin installed 'successfully' but there are 0s across the board on very sidekiq-heavy servers. We are running:

Redis server v3.0.1
Sidekiq v3.3.4

Thanks.

**Comment by garthbrydon** [comment]
@hobakill I had the same problem. I solved it by correcting my uri to include the db number e.g redis://xxx.cache.amazonaws.com:6379**/3**
